version: '3'
services:
  app:
    build:
      context: ./   
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - ./content/data:/var/lib/ghost/content/data
      - ./content/images:/var/lib/ghost/content/images
